/**
 * Portfolio List API Route
 * GET /api/portfolio/list
 * 
 * Lists all portfolios generated by the authenticated user
 * Requires authentication
 */

import { NextRequest, NextResponse } from 'next/server';
import { verifyAccessToken } from '@/lib/security/jwt';
import { getUserCompletePortfolios } from '@/lib/db/services';

export async function GET(request: NextRequest) {
  try {
    // Verify authentication
    const accessToken = request.cookies.get('accessToken')?.value;
    if (!accessToken) {
      return NextResponse.json(
        { error: 'Authentication required' },
        { status: 401 }
      );
    }
    
    const userId = verifyAccessToken(accessToken);
    if (!userId) {
      return NextResponse.json(
        { error: 'Invalid or expired token' },
        { status: 401 }
      );
    }
    
    // Get all portfolios with complete data for the user
    const portfolios = await getUserCompletePortfolios(userId);
    
    // Format response
    const formattedPortfolios = portfolios.map((item: any) => ({
      id: item.portfolio.id,
      resumeId: item.portfolio.resumeId,
      generatedAt: item.portfolio.generatedAt,
      theme: item.theme ? {
        id: item.theme.id,
        gradientCss: item.theme.gradientCss,
      } : null,
      resume: item.resume ? {
        id: item.resume.id,
        originalFilename: item.resume.originalFilename,
        uploadedAt: item.resume.uploadedAt,
      } : null,
      pages: item.pages.map((page: any) => ({
        id: page.id,
        pageType: page.pageType,
        title: page.title,
        publicUrl: page.publicUrl,
        createdAt: page.createdAt,
      })),
    }));
    
    return NextResponse.json(
      {
        portfolios: formattedPortfolios,
        count: formattedPortfolios.length,
      },
      { status: 200 }
    );
  } catch (error) {
    console.error('Portfolio list error:', error);
    
    return NextResponse.json(
      { 
        error: 'Failed to fetch portfolios',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
